server:
  port: 8079

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sjh?serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.sjh.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      update-strategy: not_empty

#图片上传
web:
  uploadpath: D:/gy/  #图片上传的路径
  load-path: file:D://gy/ #图片访问、加载的路径


logging:
  pattern:
    console: '%d{yyyy-MM-dd} [%thread] %-5level %logger- %msg%n'

#jwt配置
jwt:
  #颁发者
  issuer: sjh
  #秘钥
  secret: com.sjh
  #30分钟过期
  expiration: 30